### ISSUE TITLE
Integrated Terminal Autocomplete Color

### ISSUE THREAD

**Issue by travispamaral** [enkia/tokyo-night-vscode-theme#1]
Hey there! Great theme, loving it so far! I am noticing though the autocomplete color for zshell is pretty much impossible to see on top of the background in both VSCode and iTerm2. For iTerm I can bump up the min contrast slider and it improves but not sure how to do such changes in VSCode. Thanks!

### VSCode
![image](https://user-images.githubusercontent.com/5941111/68042571-7a5e4780-fc90-11e9-9b06-3486771c1998.png)
### iTerm2
![image](https://user-images.githubusercontent.com/5941111/68042593-8518dc80-fc90-11e9-8adf-f4f229bfd2f2.png)

**Comment by enkia** [comment]
Thanks for the feedback!

The issue is because zshell is using ansi black as the color for some reason. [Gulp uses black](https://github.com/gulpjs/gulp/issues/1766) for its timestamp too, which is a bit frustrating. 
![image](https://user-images.githubusercontent.com/255730/68056817-75b68500-fcca-11e9-9f79-127520c75985.png)

The problem is, if I change black to something else, then output like webpack's *DONE* get impacted:
![image](https://user-images.githubusercontent.com/255730/68056792-69cac300-fcca-11e9-9d1f-8aba50351298.png)

Other things that may utilize ansi black for its intended purpose may be impacted as well so I felt that black should represent black. I feel as if it's an issue with zhell/gulp as they're making an assumption that the terminal background is a light color which isn't usually the case these days aside from maybe macOS's default terminal.

Anyway, while I mull this over a bit more (I'll probably decide on using a non-black color like other themes do), you can paste this code in your settings.json to fix your immediate issue:
```javascript
"workbench.colorCustomizations": {
    "[Tokyo Night]": { // or "[Tokyo Night Storm]"
        "terminal.ansiBlack": "#7982a9",
        "terminal.ansiBrightBlack": "#7982a9" // Preferred hex color
    }
}
```

And for changing the color in iTerm: 
Preferences  > Profiles > Colors:
![image](https://user-images.githubusercontent.com/255730/68057331-ec07b700-fccb-11e9-9330-532b7051a760.png)

**Comment by enkia** [comment]
Actually, another option is to look into the framework & theme you're using for zsh. oh-my-zsh (with just git and z plugins) and the theme I'm using `~/.oh-my-zsh/custom/themes/enki.zsh-theme`) doesn't have this issue, for example: 

``` 
local ret_status="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ %s)"
function get_pwd(){
  setopt prompt_subst
  #PS1=$(shrink_path -f)
  #PS1=$(pwd | sed -e "s,^$HOME,~,")
  git_root=$PWD
  while [[ $git_root != / && ! -e $git_root/.git ]]; do
    git_root=$git_root:h
  done
  if [[ $git_root = / ]]; then
    unset git_root
	prompt_short_dir=%~
	#prompt_short_dir=$PS1
  else
    parent=${git_root%\/*}
	prompt_short_dir=${PWD#$parent/}

  fi
  echo $prompt_short_dir
}

PROMPT='$ret_status %{$fg[white]%}$(get_pwd) $(git_prompt_info)%{$reset_color%}%{$reset_color%} '

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[blue]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY=" %{$fg[yellow]%}✗%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_CLEAN=" %{$fg[green]%}✓%{$reset_color%}"
```

Looks very similar to what you're using.

**Comment by travispamaral** [comment]
Ah that makes some sense! I’ll give some of this a try Thanks!

**Comment by travispamaral** [comment]
Changing the ANSI blacks did the trick, thanks for the info! Theme is great good work!

**Comment by enkia** [comment]
Good to hear! I want to keep this open a couple more weeks in case others have thoughts to share. I’ve taken a stance on ansi black and launched with it but not entirely self-assured.
