### ISSUE TITLE
Italic keywords/comments

### ISSUE THREAD

**Issue by thany** [enkia/tokyo-night-vscode-theme#68]
Beautiful theme! Thanks for making this 😀

Except italic text doesn't look as legible to me as straight font. I'm sure this varies greatly by whatever font is used, but I *really* didn't want italics in my code and so I am humbly requesting to remove it from the theme.

It's your design of course, so I'll respect it if you don't want this changed. For this case, I also have a workaround somebody might appreciate. In the `settings.json` add this:

```json
"editor.tokenColorCustomizations": {
    "[Tokyo Night]": {
        "textMateRules": [
            {
                "scope": [
                    "comment",
                    "keyword.control.flow",
                    "meta.var.expr storage.type"
                ],
                "settings": {
                    "fontStyle": ""
                }
            }
        ]
    }
}
```

Save it, and it should do away with italics.

**Comment by enkia** [comment]
Thank you!!

I completely understand italics are either loved, tolerated, or hated.  Instead of creating a non-italic variation back when I first published, I decided instead to add a section in the readme with the snippet of settings to remove all italics. There are a few scopes you may have missed so check it out.

**Comment by thany** [comment]
Thanks! 👍🏻

Yes, I only did a cursorsy check, and accompaning fixes. Later I noticed the `async` keyword was still italic as well. I'm sure with your snippet, it'll be better.
